### PR TITLE
run isort, pyupgrade, mypy via pre-commit

### PR DESCRIPTION
**Pull request by minrk**
- adds pyupgrade, isort checks (these account for ~all autoformat changes)
- since this repo has documented mypy checks, adds mypy to pre-commit as well so they get checked in CI

### CODE REVIEW

**Comment by yuvipanda** [comment]
Can i ask we stick to black for now? :D

**Comment by minrk** [comment]
Yeah, no problem. Should I add isort, pyupgrade separately, too?

**Comment by yuvipanda** [comment]
yay, thank you @minrk :) I really appreciate your flexibility here.

**Comment by minrk** [comment]
@yuvipanda look okay, here?

**Comment by yuvipanda** [comment]
ty!

**Pull request merged**
